### ISSUE TITLE
Proguard Issue

### ISSUE THREAD

**Issue by sanrooney** [pushy-me/pushy-demo-android#10]
Hi, the pushy just working fine when using apk without proguard, but when i use proguard i get the error as below : 

E/Pushy: Creating/setting notification channel failed
    java.lang.NoSuchMethodException: a.b.f.a.e0.setChannelId [class java.lang.String]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at me.pushy.sdk.util.PushyNotifications.setNotificationChannel(PushyNotifications.java:8)
        at me.pushy.sdk.Pushy.setNotificationChannel(Pushy.java:1)
        at com.appandus.myvipmerchant.utils.PushReceiver.onReceive(PushReceiver.java:40)
        at java.lang.reflect.Method.invoke(Native Method)
        at me.pushy.sdk.model.PushyBroadcastReceiver.execute(PushyBroadcastReceiver.java:1)
        at me.pushy.sdk.util.PushyBroadcastManager.sendBroadcast(PushyBroadcastManager.java:18)
        at me.pushy.sdk.util.PushyBroadcastManager.publishNotification(PushyBroadcastManager.java:25)
        at me.pushy.sdk.util.PushyMqttConnection.messageArrived(PushyMqttConnection.java:4)
        at me.pushy.sdk.lib.paho.internal.CommsCallback.deliverMessage(CommsCallback.java:9)
        at me.pushy.sdk.lib.paho.internal.CommsCallback.handleMessage(CommsCallback.java:7)
        at me.pushy.sdk.lib.paho.internal.CommsCallback.run(CommsCallback.java:20)
        at java.lang.Thread.run(Thread.java:919)

This happens after i added the new changes for Android O+
// Automatically configure a Notification Channel for devices running Android O+
        Pushy.setNotificationChannel(builder, context);

the proguard setting already added as mentioned in the document.
sdk version used : me.pushy:sdk:1.0.55

**Comment by pushy** [comment]
Hi @sanrooney,
Thanks for reporting this issue.

We've updated our docs to resolve this issue:
https://pushy.me/docs/android/get-sdk

Please update your `proguard-rules.pro` file and add the following statements:

```
-keep class android.support.v4.app.** { *; }
```

Then, rebuild and re-run your app and the error should be resolved.
