### ISSUE TITLE
StrictMode Warning

### ISSUE THREAD

**Issue by vladaman** [pushy-me/pushy-demo-android#18]
Logcat shows strict mode warning for untagget network socket
```
 StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2182)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:54)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:374)
        at libcore.io.ForwardingOs.socket(ForwardingOs.java:216)
        at libcore.io.IoBridge.socket(IoBridge.java:654)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:128)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.connect(Socket.java:619)
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
        at me.pushy.sdk.lib.paho.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
        at me.pushy.sdk.lib.paho.internal.SSLNetworkModule.start(SSLNetworkModule.java:99)
        at me.pushy.sdk.lib.paho.internal.ClientComms$ConnectBG.run(ClientComms.java:657)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by pushy** [comment]
Hi @vladaman,
Thanks so much for reporting this issue.

Version `1.0.73` of the [Pushy Android SDK](https://pushy.me/docs/android/get-sdk) has just been released which includes a fix for this issue. Please import this new version in your app's `build.gradle`:

```
implementation 'me.pushy:sdk:1.0.73'
```

Then, rebuild and run your app, and let us know if the issue has been resolved.
